### PR TITLE
Use conan for ruby deps such as libyaml gdbm readline and libffi

### PR DESCRIPTION
**Pull request by jmarrec**
**The current status of deps on master:**

| openstudio_ruby | Windows      | Mac   | Ubuntu |
|-----------------|--------------|-------|--------|
| openssl         | Conan        | Conan | Conan  |
| zlib            | Conan        | Conan | Conan  |
| libffi          | Manual Build | Brew  | System |
| gdbm            | No           | Brew  | System |
| libyaml         | No           | Brew  | System |
| readline        | No           | Brew  | System |

**Work in Progress so far:**

| Work In Progress | Windows             | Mac    | Ubuntu |
|------------------|---------------------|--------|--------|
| openssl          | Conan               | Conan  | Conan  |
| zlib             | Conan               | Conan  | Conan  |
| libffi           | Manual Build        | Conan  | Conan  |
| Libyaml (1)      | No – won’t link     | Conan  | Conan  |
| readline         | Unavailable On MSVC | Conan  | Conan  |
| gdbm             | Unavailable On MSVC | Conan  | Conan  |
| **gmp**            | No                  | Conan | Conan |
| OpenStudio Build Status  |  OK  |  OK  | OK |
| OpenStudio Test Status  |  Cf Below  | Cf Below  | Cf Below |
| OpenStudioApplication Build Status  |  TDB  |  TDB  | TDB 

**Notes:**

* (1) A conan package for libyaml was added as part of this effort. It works for Unix but fails to link on Windows
* readline:
    * Existing recipe isn't available on MSVC
    * Need to build it from source on Mac because it doesn't support static, so if you don't build it from source it downloads a package from travis and when you build gdbm which depends on readline it'll fail to link
* gdbm recipe depends on readline hence why it isn't available on MSVC either
* gmp: It wasn’t explicitly part of the conan-openstudio-ruby build, so I didn’t realize it was needed, I'll try to have conan provide that [conan-gmp](https://github.com/bincrafters/conan-gmp): **Edit**: OK

----

## Todo:

* [x] Provide conan-gmp on Unix
* [x] Test build of OpenStudio and make sure it works
    * [x] On Linux
        * [x] Adjust find_library calls for ADDITIONAL_RUBY_LIBS: not providing any anymore
    * [x] On Mac
        * [x] Adjust find_library calls for ADDITIONAL_RUBY_LIBS: not providing any anymore
    * [x] On Windows
* [ ] Test build of OpenStudioApplication and make sure it works
    * [ ] On Linux
    * [ ] On Mac
    * [ ] On Windows

### CODE REVIEW

**Comment by jmarrec** [comment]
@kbenne @macumber @tijcolem @lefticus See current status in OP

**Comment by jmarrec** [comment]
Mac getting a ld warning: `ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame`

Getting it in the build of conan-openstudio-ruby too actually.

**Comment by jmarrec** [comment]
One thing I need to mention that's pretty important is that if you try right now with this branch + my jmarrec/OpenStudio/OS_App_killswitch, you should expect some potential problems due to conan dependencies etc. I'm testing three platforms at once and forking some conan recipes constantly, so I can't say everything will work 100% without deleting some recipes etc. Ping me if you run into this.

**Comment by jmarrec** [comment]
## Mac:

```
$ ctest -j`nproc`

The following tests FAILED:
        205 - CoreFixture.Path_toString (Failed)
        211 - CoreFixture.IsNetworkPath (Failed)
        531 - BCLFixture.LocalBCL_AuthKey (Failed)
        533 - BCLFixture.RemoteBCLTest2 (Failed)
        537 - BCLFixture.BCLXML_New (Failed)
        538 - BCLFixture.BCLComponent (Failed)
        539 - BCLFixture.BCLFileReference (Failed)
        540 - BCLFixture.BCLMeasure (Failed)
        541 - BCLFixture.BCLMeasure_CTor (Failed)
        1731 - ModelFixture.ScheduleFile (SEGFAULT)
        1842 - ModelFixture.Space_intersectSurfaces_degenerate1 (Failed)
        1843 - ModelFixture.Space_intersectSurfaces_degenerate2 (Failed)
        1844 - ModelFixture.Space_intersectSurfaces_degenerate3 (Failed)
        1966 - ModelFixture.ThreeJSReverseTranslator_FloorplanJS_SimAUD_Paper (Failed)
        2167 - EnergyPlusFixture.ReverseTranslatorSensor1_EMS (Failed)
        2169 - EnergyPlusFixture.ReverseTranslatorSensor2_EMS (Failed)
        2171 - EnergyPlusFixture.ReverseTranslatorSensor_Meter_EMS (Failed)
        2173 - EnergyPlusFixture.ReverseTranslatorActuator_EMS (Failed)
        2183 - EnergyPlusFixture.ReverseTranslatorProgram_EMS (Failed)
        2185 - EnergyPlusFixture.ReverseTranslatorSubroutine_EMS (Failed)
        2187 - EnergyPlusFixture.ReverseTranslatorProgramCallingManager_EMS (Failed)
        2190 - EnergyPlusFixture.ReverseTranslatorOutput_EMS (Failed)
        2192 - EnergyPlusFixture.ReverseTranslatorGlobalVariable_EMS (Failed)
        2196 - EnergyPlusFixture.ReverseTranslatorOutputVariable_EMS (Failed)
        2198 - EnergyPlusFixture.ReverseTranslatorTrendVariable_EMS (Failed)
        2201 - EnergyPlusFixture.ReverseTranslatorInternalVariable_EMS (Failed)
        2203 - EnergyPlusFixture.ReverseTranslatorConstructionIndexVariable_EMS (Failed)
        2205 - EnergyPlusFixture.ReverseTranslatorCurveOrTableIndexVariable_EMS (Failed)
        2208 - EnergyPlusFixture.ReverseTranslatorMeteredOutputVariable_EMS (Failed)
        2210 - EnergyPlusFixture.ReverseTranslatorTrendVariable2_EMS (Failed)
        2422 - CLITest-test_bundle-bundle_native (Failed)
        2425 - CLITest-test_bundle-bundle_default (Failed)
```

**Comment by jmarrec** [comment]
## Windows 

### CLITest only

```
$ ctest -j12 -C Debug

The following tests FAILED:
        150 - IlluminanceMapFixture.IlluminanceMapPlotMin (Failed)
        162 - SqlFileFixture.TimeSeries (Failed)
        531 - BCLFixture.LocalBCL_AuthKey (Failed)
        533 - BCLFixture.RemoteBCLTest2 (Failed)
        540 - BCLFixture.BCLMeasure (Failed)
        541 - BCLFixture.BCLMeasure_CTor (Failed)
        1731 - ModelFixture.ScheduleFile (Failed)
        1842 - ModelFixture.Space_intersectSurfaces_degenerate1 (Failed)
        1843 - ModelFixture.Space_intersectSurfaces_degenerate2 (Failed)
        1844 - ModelFixture.Space_intersectSurfaces_degenerate3 (Failed)
        1966 - ModelFixture.ThreeJSReverseTranslator_FloorplanJS_SimAUD_Paper (Failed)
        2167 - EnergyPlusFixture.ReverseTranslatorSensor1_EMS (Failed)
        2169 - EnergyPlusFixture.ReverseTranslatorSensor2_EMS (Failed)
        2171 - EnergyPlusFixture.ReverseTranslatorSensor_Meter_EMS (Failed)
        2173 - EnergyPlusFixture.ReverseTranslatorActuator_EMS (Failed)
        2183 - EnergyPlusFixture.ReverseTranslatorProgram_EMS (Failed)
        2185 - EnergyPlusFixture.ReverseTranslatorSubroutine_EMS (Failed)
        2187 - EnergyPlusFixture.ReverseTranslatorProgramCallingManager_EMS (Failed)
        2190 - EnergyPlusFixture.ReverseTranslatorOutput_EMS (Failed)
        2192 - EnergyPlusFixture.ReverseTranslatorGlobalVariable_EMS (Failed)
        2196 - EnergyPlusFixture.ReverseTranslatorOutputVariable_EMS (Failed)
        2198 - EnergyPlusFixture.ReverseTranslatorTrendVariable_EMS (Failed)
        2201 - EnergyPlusFixture.ReverseTranslatorInternalVariable_EMS (Failed)
        2203 - EnergyPlusFixture.ReverseTranslatorConstructionIndexVariable_EMS (Failed)
        2205 - EnergyPlusFixture.ReverseTranslatorCurveOrTableIndexVariable_EMS (Failed)
        2208 - EnergyPlusFixture.ReverseTranslatorMeteredOutputVariable_EMS (Failed)
        2210 - EnergyPlusFixture.ReverseTranslatorTrendVariable2_EMS (Failed)
        2420 - CLITest-test_bundle-bundle (Failed)
        2421 - CLITest-test_bundle-bundle_git (Failed)
        2425 - CLITest-test_bundle-bundle_default (Failed)
```

**Comment by jmarrec** [comment]
## Ubuntu (16.04)


```
$ ctest -j`nproc`

The following tests FAILED:
	152 - IlluminanceMapFixture.IlluminanceMapPlotMinMax (Failed)
	153 - IlluminanceMapFixture.IlluminanceMapPlotRefPts (Child aborted)
	154 - IlluminanceMapFixture.IlluminanceMapPlotSeriesCount (Failed)
	155 - IlluminanceMapFixture.IlluminanceMapPlotSeries (Failed)
	156 - IlluminanceMapFixture.IlluminanceMapPlotSeriesOpt (Failed)
	205 - CoreFixture.Path_toString (Failed)
	211 - CoreFixture.IsNetworkPath (Failed)
	232 - UpdateManager.GeneralTest (SIGTRAP)
	233 - UpdateManager.ExpandedTest (SIGTRAP)
	531 - BCLFixture.LocalBCL_AuthKey (SIGTRAP)
	532 - BCLFixture.RemoteBCLTest (SIGTRAP)
	533 - BCLFixture.RemoteBCLTest2 (SIGTRAP)
	534 - BCLFixture.GetComponentByUID (SIGTRAP)
	535 - BCLFixture.RemoteBCLMetaSearchTest (SIGTRAP)
	540 - BCLFixture.BCLMeasure (Failed)
	1731 - ModelFixture.ScheduleFile (SEGFAULT)
	1842 - ModelFixture.Space_intersectSurfaces_degenerate1 (Failed)
	1843 - ModelFixture.Space_intersectSurfaces_degenerate2 (Failed)
	1844 - ModelFixture.Space_intersectSurfaces_degenerate3 (Failed)
	1966 - ModelFixture.ThreeJSReverseTranslator_FloorplanJS_SimAUD_Paper (Failed)
	2167 - EnergyPlusFixture.ReverseTranslatorSensor1_EMS (Failed)
	2169 - EnergyPlusFixture.ReverseTranslatorSensor2_EMS (Failed)
	2171 - EnergyPlusFixture.ReverseTranslatorSensor_Meter_EMS (Failed)
	2173 - EnergyPlusFixture.ReverseTranslatorActuator_EMS (Failed)
	2183 - EnergyPlusFixture.ReverseTranslatorProgram_EMS (Failed)
	2185 - EnergyPlusFixture.ReverseTranslatorSubroutine_EMS (Failed)
	2187 - EnergyPlusFixture.ReverseTranslatorProgramCallingManager_EMS (Failed)
	2190 - EnergyPlusFixture.ReverseTranslatorOutput_EMS (Failed)
	2192 - EnergyPlusFixture.ReverseTranslatorGlobalVariable_EMS (Failed)
	2196 - EnergyPlusFixture.ReverseTranslatorOutputVariable_EMS (Failed)
	2198 - EnergyPlusFixture.ReverseTranslatorTrendVariable_EMS (Failed)
	2201 - EnergyPlusFixture.ReverseTranslatorInternalVariable_EMS (Failed)
	2203 - EnergyPlusFixture.ReverseTranslatorConstructionIndexVariable_EMS (Failed)
	2205 - EnergyPlusFixture.ReverseTranslatorCurveOrTableIndexVariable_EMS (Failed)
	2208 - EnergyPlusFixture.ReverseTranslatorMeteredOutputVariable_EMS (Failed)
	2210 - EnergyPlusFixture.ReverseTranslatorTrendVariable2_EMS (Failed)
	2420 - CLITest-test_bundle-bundle (Failed)
	2421 - CLITest-test_bundle-bundle_git (Failed)
	2422 - CLITest-test_bundle-bundle_native (Failed)
	2425 - CLITest-test_bundle-bundle_default (Failed)
```

**Comment by macumber** [comment]
Thanks for the very detailed report @jmarrec.  If I understand correctly, this PR is just about ready to merge.  It also seems like it provides all the minimum required extensions (that we have on develop) + some additional ones (escape, fiddle, wait, openssl).  So I suggest that we merge this PR and focus on using this for our release next week. 

All of the items you identified as optional next steps are good, we should add issues to work on those after our deliverable.  Does that sound right to both of you @jmarrec @tijcolem ?

**Comment by jmarrec** [comment]
@macumber Ok test results for OpenStudio at least came back similar on all platforms, can't see anything very frigthening. So I think we can merge this one

**Pull request merged**
