### PR TITLE
Scope out the update to ruby 2.7.2

### PR DESCRIPTION
**Pull request by jmarrec**

### CODE REVIEW

**Comment by jmarrec** [comment]
I made adjustments for Ubuntu, and both Ubuntu and mac appear "happy" now: https://travis-ci.org/github/NREL/conan-openstudio-ruby/builds/741142824. (I say "happy" because it will correctly link and  issue `openstudio --help`. The embedded gems I am testing the package with would need to be updated to 2.7.2 to match so the tests could have a change of succeeding.)


Windows, as usual...

```bash
x64-vcruntime140-ruby270-static.lib(load.obj) : error LNK2001: unresolved external symbol rb_hasFile [C:\Users\appveyor\.conan\data\openstudio_ruby\2.7.2\nrel\testing\build\45b3b9a1aa73fdb3ff32afdc2b2ddc0affca7928\Ruby.vcxproj]
x64-vcruntime140-ruby270-static.lib(load.obj) : error LNK2001: unresolved external symbol rb_require_embedded [C:\Users\appveyor\.conan\data\openstudio_ruby\2.7.2\nrel\testing\build\45b3b9a1aa73fdb3ff32afdc2b2ddc0affca7928\Ruby.vcxproj]
x64-vcruntime140-ruby270.dll : fatal error LNK1120: 2 unresolved externals [C:\Users\appveyor\.conan\data\openstudio_ruby\2.7.2\nrel\testing\build\45b3b9a1aa73fdb3ff32afdc2b2ddc0affca7928\Ruby.vcxproj]
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\cl.EXE"' : return code '0x2' [C:\Users\appveyor\.conan\data\openstudio_ruby\2.7.2\nrel\testing\build\45b3b9a1aa73fdb3ff32afdc2b2ddc0affca7928\Ruby.vcxproj]
  Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\nmake.EXE"' : return code '0x2' [C:\Users\appveyor\.conan\data\openstudio_ruby\2.7.2\nrel\testing\build\45b3b9a1aa73fdb3ff32afdc2b2ddc0affca7928\Ruby.vcxproj]
  Stop.
NMAKE : warning U4010: 'build-ext' : build failed; /K specified, continuing ... [C:\Users\appveyor\.conan\data\openstudio_ruby\2.7.2\nrel\testing\build\45b3b9a1aa73fdb3ff32afdc2b2ddc0affca7928\Ruby.vcxproj]

```

**Comment by tijcolem** [comment]
In regards to those undefined symbols. 

```
64-vcruntime140-ruby270-static.lib(load.obj) : error LNK2001: unresolved external symbol rb_hasFile [C:\Users\appveyor\.conan\data\openstudio_ruby\2.7.2\nrel\testing\build\45b3b9a1aa73fdb3ff32afdc2b2ddc0affca7928\Ruby.vcxproj]
x64-vcruntime140-ruby270-static.lib(load.obj) : error LNK2001: unresolved external symbol rb_require_embedded [C:\Users\appveyor\.conan\data\openstudio_ruby\2.7.2\nrel\testing\build\45b3b9a1aa73fdb3ff32afdc2b2ddc0affca7928\Ruby.vcxproj]
```
It might be due to some changes in the win32/Makefile.sub in 2.7.2 vs 2.5.5. The linker might be missing a lib. 
In particular, maybe these options might need to be tweaked on conan side to reflect these changes. 

Screen Shot 2021-01-26 at 6 30 43 PM

On my local machine it fails on this step. 


  ```
 Creating library dummy.lib and object dummy.exp
x64-vcruntime140-ruby270-static.lib(load.obj) : error LNK2001: unresolved external symbol rb_hasFile [C:\Users\Administ
rator\.conan\data\openstudio_ruby\2.7.2\bincrafters\testing\build\2948faa5fb7a5424ed8be9bde9fe458549bfc1ba\Ruby.vcxproj
]
x64-vcruntime140-ruby270-static.lib(load.obj) : error LNK2001: unresolved external symbol rb_require_embedded [C:\Users
\Administrator\.conan\data\openstudio_ruby\2.7.2\bincrafters\testing\build\2948faa5fb7a5424ed8be9bde9fe458549bfc1ba\Rub
y.vcxproj]
x64-vcruntime140-ruby270.dll : fatal error LNK1120: 2 unresolved externals [C:\Users\Administrator\.conan\data\openstud
io_ruby\2.7.2\bincrafters\testing\build\2948faa5fb7a5424ed8be9bde9fe458549bfc1ba\Ruby.vcxproj]
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bi
n\HostX64\x64\cl.EXE"' : return code '0x2' [C:\Users\Administrator\.conan\data\openstudio_ruby\2.7.2\bincrafters\testin
g\build\2948faa5fb7a5424ed8be9bde9fe458549bfc1ba\Ruby.vcxproj]
```

And here is the diff I see when looking in the conan build directories. 

2.5.5/bincrafters/testing/build/2948faa5fb7a5424ed8be9bde9fe458549bfc1ba/Ruby-prefix/src/Ruby/win32/Makefile.sub

```
$(LIBRUBY_SO):  $(LIBRUBY_A) $(DLDOBJS) $(RUBYDEF) $(RUBY_SO_NAME).res
                @echo $(DLDOBJS)
                @-$(PRE_LIBRUBY_UPDATE)
                $(ECHO) linking shared-library $(@:\=/)
                $(Q) $(LDSHARED) $(MAINOBJ) $(DLDOBJS) $(LIBRUBY_A) \
                        $(RUBY_SO_NAME).res $(SOLIBS) $(EXTSOLIBS) $(LIBS) -Fe$@ -link $(LDFLAGS) \
                        $(LIBRUBY_DLDFLAGS)
                @$(RM) dummy.lib dummy.exp
                $(Q) $(LDSHARED_0)
                $(Q) $(LDSHARED_1)
                $(Q) $(LDSHARED_2)
# | findstr -v -c:LNK4049 -c:LNK4217
```

**VS** 

2.7.2/bincrafters/testing/build/2948faa5fb7a5424ed8be9bde9fe458549bfc1ba/Ruby-prefix/src/Ruby/win32/Makefile.sub

```
$(LIBRUBY_SO):  $(LIBRUBY_A) $(DLDOBJS) $(RUBYDEF) $(RUBY_SO_NAME).res
                @echo $(DLDOBJS)
!if "$(EXTSTATIC)" == ""
                @-$(PRE_LIBRUBY_UPDATE)
!endif
                $(ECHO) linking shared-library $(@:\=/)
                $(Q) $(LDSHARED) $(DLDOBJS) $(LIBRUBY_A) \
                        $(RUBY_SO_NAME).res $(SOLIBS) $(EXTSOLIBS) $(LIBS) -Fe$@ -link $(LDFLAGS) \
                        $(LIBRUBY_DLDFLAGS)
                @$(RM) dummy.lib dummy.exp
                $(Q) $(LDSHARED_0)
                $(Q) $(LDSHARED_1)
                $(Q) $(LDSHARED_2)
# | findstr -v -c:LNK4049 -c:LNK4217

```

**Comment by tijcolem** [comment]
I think this is the reason (below).  In the v2.7.2 they left off `$(MAINOBJ)` when linking for windows,. Not sure if this was on purpose, but in our case, the injected functions/symbols `rb_require_embedded` and `rb_hasFile` are not resolving due to this so I added this back in.  

I did some testing locally and got windows to build using a custom ruby.tar.gz.  If this build works, next step is to apply a proper patch and maybe clean up the other patches that correspond to this `win32/Makefile.sub` as there are several patches for this file. 



Screen Shot 2021-01-27 at 8 57 45 PM

**Comment by jmarrec** [comment]
@tijcolem amazing detective work! (And thanks for explanation, I hope I'll learn something from it!)

**Pull request merged**
