### PR TITLE
Allow build on Mac and simplify conan file

### PR DESCRIPTION
**Pull request by jmarrec**
I made the conanfile.py rely on globbing instead of harcoding include dirs and library names. I was getting an error on mac because it didn't find the `ruby/config.h`, as the include folder is platform dependent and was only set for linux and windows.

I also updated conan-cmake to v0.14 to match the OpenStudio CMakeLists.txt.

I uploaded it to my bintray `openstudio_ruby/2.5.5@jmarrec/testing` but since it has the same version as the one before, **you will need to manually remove any prior openstudio_ruby or it won't download the new version**

### CODE REVIEW

**Comment by jmarrec** [comment]
FYI, I noticed that linux produces 41 libraries (.a), mac only 40.

mac is missing `gdbm.a` compared to linux, not sure if that's normal/if it matters.

Edit: might need something to search in Homebrew's path:
```
find_library(GDBM libgdbm.a PATHS /usr/local/Cellar/gdbm /usr/local/opt/gdbm/lib)
```

**Comment by jmarrec** [comment]
I added `find_library(gdbm ...` call which uses `NO_DEFAULT_PATH` so that it will find homebrew's GDBM, and passing `--with-gdbm-dir` to the ruby configure step. I now have the `gdbm.a` that's produced on Mac.

**Comment by macumber** [comment]
@tijcolem FYI, see the note about gdbm.a

**Comment by lefticus** [comment]
The PR looks good to me, simplifies some aspects, fixes others.

**Pull request merged**
