### PR TITLE
Add test_package that builds our CLI 

### LINKED ISSUE #15: Add test_package that mimics our CLI
**Perhaps** instead of waiting for things to break on OpenStudio's side, we should create a `test_package` (cf https://conan-docs.readthedocs.io/en/feature-cmake-toolchain-file/reference/commands/test_package.html) that would actually compile a **small** cpp program and link against our conan openstudio_ruby

That would automatically be run on travis/appveyor via conan-package-tools, and could help catch problems early on without having to recompile a much larger program like OpenStudio.

### PR DESCRIPTION
**Pull request by jmarrec**
Fix #15: adding an actual CLI. I am using conan swig_installer (4.0.0) for this which works fine (but it's not swigging model objects though), cf https://github.com/NREL/conan-openstudio-ruby/issues/8

It's a CLI that has most of openstudio's CLI, except openstudio-specific stuff (like ApplyMeasure, Run, Update).
It should hopefully help us:
* Catch things that break early on, before we notice it on OpenStudio's side
* Allow us to test/debug cli ruby specific issues (encodings, gem_install, interactive, etc)

interactive appears to work on my Ubuntu machine, gem_install doesn't

### CODE REVIEW

**Comment by jmarrec** [comment]
Weird, on my machine all tests are passing (Ubuntu 18.04; gcc7).

On travis, two are failing:

 * test/test_bundle.rb: test_bundle
 * test/test_bundle.rb: test_bundle_git

**Comment by jmarrec** [comment]
Status as of right now:

Windows isn't linking agaisnt the CLI, but that's probably because I removed macro stuff around fiddle etc.
Mac is moissing core foundation problably (which I just readded, not sure if that suffices), and Ubuntu is failing two tests that are working on my machine.

**Comment by jmarrec** [comment]
@macumber Mac and Unix are "fine" (`test_bundle_git` and `test_bundle` are failing, not sure why).

On Windows, the CLI is built properly, and can be used to display help, and simple `openstudio -e "puts 'helloworld'"`. So that's good news already!

The bad news is that all other tests are failing since it can't load `minitest`:
```
Error: cannot load such file -- minitest/autorun in eval:99:in `require'
```
(cf https://ci.appveyor.com/project/ci-commercialbuildings/conan-openstudio-ruby/builds/26742468/job/qtmjb35larf39hwp#L9189)

I wouldn't know where to start to fix this minitest missing thing, but you probably do.

**Comment by jmarrec** [comment]
So apparently minitest isn't inclued on windows, while it is on unix.

I added something that will basically download the openstudio3-gems.tar.gz from s3 (like OS does), to embed some gems, and that includes minitest. It also includes a bunch of other stuff that isn't needed in this context, so I would ideally host a separate minimal tar.gz on s3 that isn't 47MB.
The other reason to have a minimal one, is because I actually HAVE to delete the openstudo-specific ones since it will largely go over MAX_PATH given the nature of the build directory for conan, with the sha etc. Eg in my case files are generated in a folder that's already 145 chars to begin with.

```
C:\Users\julien\Software\Others\conan\conan-openstudio-ruby\test_package\build\ecbfb49a4e2ea8618319be5f9e02c8e0621391fb\embedded_files\ruby\2.5.0
```

**Now all tests but 4 are running on WIndows**.

```
openstudio_ruby/2.5.5@nrel/testing (test package): 30 tests Passed:
 * test\test_bundle.rb: test_bundle_native
 * test\test_embedded_help.rb: test_dir_glob
 * test\test_embedded_ruby.rb: test_io_open_null_device
 * test\test_embedded_ruby.rb: test_encodings
 * test\test_embedded_ruby.rb: test_bigdecimal
 * test\test_embedded_ruby.rb: test_continuation
 * test\test_embedded_ruby.rb: test_coverage
 * test\test_embedded_ruby.rb: test_cparse
 * test\test_embedded_ruby.rb: test_date_core
 * test\test_embedded_ruby.rb: test_etc
 * test\test_embedded_ruby.rb: test_fiber
 * test\test_embedded_ruby.rb: test_fiddle
 * test\test_embedded_ruby.rb: test_generator
 * test\test_embedded_ruby.rb: test_md5
 * test\test_embedded_ruby.rb: test_nkf
 * test\test_embedded_ruby.rb: test_objspace
 * test\test_embedded_ruby.rb: test_pathname
 * test\test_embedded_ruby.rb: test_pysch
 * test\test_embedded_ruby.rb: test_ripper
 * test\test_embedded_ruby.rb: test_rmd160
 * test\test_embedded_ruby.rb: test_sdbm
 * test\test_embedded_ruby.rb: test_sha1
 * test\test_embedded_ruby.rb: test_sha2
 * test\test_embedded_ruby.rb: test_stringio
 * test\test_embedded_ruby.rb: test_strscan
 * test\test_embedded_ruby.rb: test_zlib
 * test\test_embedded_ruby.rb: test_openssl
 * test\test_encodings.rb: test_encoding
 * test\test_encodings.rb: test_encoding2
 * test\test_encodings.rb: test_encoding_external

openstudio_ruby/2.5.5@nrel/testing (test package): ERROR: 4 tests Failed:
 * test\test_bundle.rb: test_bundle
 * test\test_bundle.rb: test_bundle_git
 * test\test_bundle.rb: test_bundle_no_install
 * test\test_bundle.rb: test_no_bundle
```

**Comment by jmarrec** [comment]
I made a modified branch here that builds a minimal set of gems, takes only 2MB (openstudio-standards was most likely the heaviest): https://github.com/jmarrec/openstudio-gems/tree/develop3-minimal

I added this tar.gz to git here directly (in `test_package/dependencies/openstudio3-gems-minimal-20191015.tar.g`), so it can be used easily for testing.

**Comment by tijcolem** [comment]
I'd like to set up CI on this. I'm assuming we can create one platform (ideally Linux) to use as the testbed for this or do we want all platforms? I can create an initial job in Jenkins. Assuming this is a cmake project, can it use the default options and just run cmd below?  

 `$cd build && cmake .../`

**Comment by jmarrec** [comment]
Travis and appveyor are already configured and run the tests automatically. I think Jenkins isn't necessary for this. We should get the test passing or disable the failing ones before this goes live as the upload to bintray won't happen with failing tests (not sure about this)

**Comment by tijcolem** [comment]
Okay, I knew Travis and Appveyor were configured but I thought that was to build just openstudio_ruby. I thought the CLI build was a separate process. Looks like travis is passing. 
I'll checkout appveyor.

**Pull request merged**
