### PR TITLE
Update ruby installer and remotes

### PR DESCRIPTION
**Pull request by jmarrec**

### CODE REVIEW

**Comment by jmarrec** [comment]
I have no clue why Github actions is hanging like this on MSVC ?! It works just fine locally

**Comment by macumber** [comment]
There is a warning saying "The windows-2016 environment is deprecated and will be removed on March 15, 2022. Migrate to windows-latest instead. For more details see https://github.com/actions/virtual-environments/issues/4312" that is possibly related?

I see you tried re-running once, maybe you could try re-running again in case this brownout was the issue?

https://twitter.com/github/status/1420097157885988867?lang=en

**Comment by jmarrec** [comment]
The release build is working fine.
It's the DEBUG one that hangs at "generating parse.c". I hadn't tried Debug locally, will do.

**Comment by jmarrec** [comment]
Ah, there you go:

Screen Shot 2022-01-14 at 13 35 48

**Comment by jmarrec** [comment]
This is likely due to the fact that I uploaded a new version (recipe revision) of the bison/3.7.1 package on NREL's artifactory.

This new one fails: https://conan.commercialbuildings.dev/ui/repos/tree/General/openstudio%2F_%2Fbison%2F3.7.1%2F_%2F8bba3cd5416cf47dbc99130108ecb67e

If I pin it exactly to the former one, it works: ad29e804e82c8b6d58765096676b5a5e

...

**Comment by jmarrec** [comment]
THe bottom line is that the old bison revision uses m4/1.4.18 and the new one uses m4/1.4.19. So something changed there

**Review by tijcolem — APPROVED** [review]
Looks good!  We'll sit on MSVC 2022 for now.

**Pull request merged**
